### ISSUE TITLE
Add conditions on config key section

### ISSUE THREAD

**Issue by NosillaCast** [bbusschots/xkpasswd.pm#8]
Config key section does _clearly_ not specify which are mandatory.

**Comment by bbusschots** [comment]
The entire section of the documentation about configs has been re-written and re-structured, hopefully offering more clarity. The changes are in the latest commit to the CPAN-Prep branch: https://github.com/bbusschots/xkpasswd.pm/commit/f49563fdacd6c558e39062bb3270dce01a4f0b0a
